// <auto-generated />
using System;
using Forklaringsmodell.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forklaringsmodell.Infrastructure.Migrations
{
    [DbContext(typeof(ForklaringsmodellDbContext))]
    [Migration("20260723114209_UtfallOgVilkarGrunnlagstype")]
    partial class UtfallOgVilkarGrunnlagstype
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Faktum", b =>
                {
                    b.Property<Guid>("FaktumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AvledetFraFaktumId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("InnhentetTidspunkt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KildeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SakId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Struktur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Verdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FaktumId");

                    b.HasIndex("AvledetFraFaktumId");

                    b.HasIndex("KildeId");

                    b.HasIndex("SakId");

                    b.ToTable("Faktum", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.FaktumRettskilde", b =>
                {
                    b.Property<Guid>("FaktumId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RettskildeId")
                        .HasColumnType("TEXT");

                    b.HasKey("FaktumId", "RettskildeId");

                    b.HasIndex("RettskildeId");

                    b.ToTable("FaktumRettskilde", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Forklaringslogg", b =>
                {
                    b.Property<Guid>("LoggId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VedtakId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoggId");

                    b.HasIndex("VedtakId")
                        .IsUnique();

                    b.ToTable("Forklaringslogger", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.ForklaringsloggOppforing", b =>
                {
                    b.Property<Guid>("OppforingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LoggId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReferanseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("OppforingId");

                    b.HasIndex("LoggId");

                    b.HasIndex("Type", "ReferanseId");

                    b.ToTable("ForklaringsloggOppforinger", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Kilde", b =>
                {
                    b.Property<Guid>("KildeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Autoritativ")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CccevReferanse")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("KildeId");

                    b.ToTable("Kilder", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.KildeRettskilde", b =>
                {
                    b.Property<Guid>("KildeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RettskildeId")
                        .HasColumnType("TEXT");

                    b.HasKey("KildeId", "RettskildeId");

                    b.HasIndex("RettskildeId");

                    b.ToTable("KildeRettskilde", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Partsmedvirkning", b =>
                {
                    b.Property<Guid>("MedvirkningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Innhold")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SakId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Tidspunkt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("MedvirkningId");

                    b.HasIndex("SakId");

                    b.ToTable("Partsmedvirkninger", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Regel", b =>
                {
                    b.Property<Guid>("RegelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CpsvRegelReferanse")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegeldefinisjonReferanse")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Teknologi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("RegelId");

                    b.ToTable("Regler", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.RegelRettskilde", b =>
                {
                    b.Property<Guid>("RegelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RettskildeId")
                        .HasColumnType("TEXT");

                    b.HasKey("RegelId", "RettskildeId");

                    b.HasIndex("RettskildeId");

                    b.ToTable("RegelRettskilde", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Rettskilde", b =>
                {
                    b.Property<Guid>("RettskildeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EliReferanse")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Henvisning")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("VersjonDato")
                        .HasColumnType("TEXT");

                    b.HasKey("RettskildeId");

                    b.ToTable("Rettskilder", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Sak", b =>
                {
                    b.Property<Guid>("SakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CpsvTjenesteReferanse")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Opprettet")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SistEndret")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tittel")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UtlosendeHendelse")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("SakId");

                    b.ToTable("Saker", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.SakRelasjon", b =>
                {
                    b.Property<Guid>("RelasjonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RelatertSakId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SakId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("RelasjonId");

                    b.HasIndex("RelatertSakId");

                    b.HasIndex("SakId");

                    b.ToTable("SakRelasjoner", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Vedtak", b =>
                {
                    b.Property<Guid>("VedtakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AutomatiseringsGrad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SakId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Tidspunkt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Utfall")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("VedtakId");

                    b.HasIndex("SakId");

                    b.ToTable("Vedtak", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Vedtaksvirkning", b =>
                {
                    b.Property<Guid>("VirkningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AvledetFraVirkningId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Belop")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Beskrivelse")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fastsettelsesmate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("GyldigFra")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("GyldigTil")
                        .HasColumnType("TEXT");

                    b.Property<string>("LopendeVilkar")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RapporteringsFrekvens")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Varighet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VedtakId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VilkarId")
                        .HasColumnType("TEXT");

                    b.HasKey("VirkningId");

                    b.HasIndex("AvledetFraVirkningId");

                    b.HasIndex("VedtakId");

                    b.HasIndex("VilkarId");

                    b.ToTable("Vedtaksvirkninger", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.VedtaksvirkningFaktum", b =>
                {
                    b.Property<Guid>("VirkningId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FaktumId")
                        .HasColumnType("TEXT");

                    b.HasKey("VirkningId", "FaktumId");

                    b.HasIndex("FaktumId");

                    b.ToTable("VedtaksvirkningFaktum", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.VedtaksvirkningVurdering", b =>
                {
                    b.Property<Guid>("VirkningId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VurderingId")
                        .HasColumnType("TEXT");

                    b.HasKey("VirkningId", "VurderingId");

                    b.HasIndex("VurderingId");

                    b.ToTable("VedtaksvirkningVurdering", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Vilkar", b =>
                {
                    b.Property<Guid>("VilkarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CpsvTjenesteReferanse")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fastsettelsesmate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Grunnlagstype")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kodeverk")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RegelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardTekst")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("VilkarId");

                    b.HasIndex("RegelId");

                    b.ToTable("Vilkar", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.VilkarRettskilde", b =>
                {
                    b.Property<Guid>("VilkarId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RettskildeId")
                        .HasColumnType("TEXT");

                    b.HasKey("VilkarId", "RettskildeId");

                    b.HasIndex("RettskildeId");

                    b.ToTable("VilkarRettskilde", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Vurdering", b =>
                {
                    b.Property<Guid>("VurderingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beregningsspor")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Eskalert")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ForkastedeUtfall")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hovedhensyn")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Konfidens")
                        .HasPrecision(3, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SakId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Utfall")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("VurderingId");

                    b.HasIndex("RegelId");

                    b.HasIndex("SakId");

                    b.ToTable("Vurderinger", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.VurderingFaktum", b =>
                {
                    b.Property<Guid>("VurderingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FaktumId")
                        .HasColumnType("TEXT");

                    b.HasKey("VurderingId", "FaktumId");

                    b.HasIndex("FaktumId");

                    b.ToTable("VurderingFaktum", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.VurderingReferanse", b =>
                {
                    b.Property<Guid>("VurderingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RefererteVurderingId")
                        .HasColumnType("TEXT");

                    b.HasKey("VurderingId", "RefererteVurderingId");

                    b.HasIndex("RefererteVurderingId");

                    b.ToTable("VurderingReferanse", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.VurderingRettskilde", b =>
                {
                    b.Property<Guid>("VurderingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RettskildeId")
                        .HasColumnType("TEXT");

                    b.HasKey("VurderingId", "RettskildeId");

                    b.HasIndex("RettskildeId");

                    b.ToTable("VurderingRettskilde", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Faktum", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Faktum", "AvledetFraFaktum")
                        .WithMany("Avledninger")
                        .HasForeignKey("AvledetFraFaktumId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Forklaringsmodell.Domain.Entities.Kilde", "Kilde")
                        .WithMany("Faktum")
                        .HasForeignKey("KildeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Forklaringsmodell.Domain.Entities.Sak", "Sak")
                        .WithMany("Faktum")
                        .HasForeignKey("SakId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AvledetFraFaktum");

                    b.Navigation("Kilde");

                    b.Navigation("Sak");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.FaktumRettskilde", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Faktum", "Faktum")
                        .WithMany("FaktumRettskilde")
                        .HasForeignKey("FaktumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Forklaringsmodell.Domain.Entities.Rettskilde", "Rettskilde")
                        .WithMany("FaktumRettskilde")
                        .HasForeignKey("RettskildeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faktum");

                    b.Navigation("Rettskilde");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Forklaringslogg", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Vedtak", "Vedtak")
                        .WithOne("Forklaringslogg")
                        .HasForeignKey("Forklaringsmodell.Domain.Entities.Forklaringslogg", "VedtakId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vedtak");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.ForklaringsloggOppforing", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Forklaringslogg", "Forklaringslogg")
                        .WithMany("Oppforinger")
                        .HasForeignKey("LoggId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Forklaringslogg");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.KildeRettskilde", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Kilde", "Kilde")
                        .WithMany("KildeRettskilde")
                        .HasForeignKey("KildeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Forklaringsmodell.Domain.Entities.Rettskilde", "Rettskilde")
                        .WithMany("KildeRettskilde")
                        .HasForeignKey("RettskildeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kilde");

                    b.Navigation("Rettskilde");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Partsmedvirkning", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Sak", "Sak")
                        .WithMany("Partsmedvirkninger")
                        .HasForeignKey("SakId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sak");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.RegelRettskilde", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Regel", "Regel")
                        .WithMany("RegelRettskilde")
                        .HasForeignKey("RegelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Forklaringsmodell.Domain.Entities.Rettskilde", "Rettskilde")
                        .WithMany("RegelRettskilde")
                        .HasForeignKey("RettskildeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Regel");

                    b.Navigation("Rettskilde");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.SakRelasjon", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Sak", "RelatertSak")
                        .WithMany()
                        .HasForeignKey("RelatertSakId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Forklaringsmodell.Domain.Entities.Sak", "Sak")
                        .WithMany("Relasjoner")
                        .HasForeignKey("SakId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RelatertSak");

                    b.Navigation("Sak");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Vedtak", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Sak", "Sak")
                        .WithMany("Vedtak")
                        .HasForeignKey("SakId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sak");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Vedtaksvirkning", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Vedtaksvirkning", "AvledetFraVirkning")
                        .WithMany("AvledeteVirkninger")
                        .HasForeignKey("AvledetFraVirkningId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Forklaringsmodell.Domain.Entities.Vedtak", "Vedtak")
                        .WithMany("Virkninger")
                        .HasForeignKey("VedtakId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Forklaringsmodell.Domain.Entities.Vilkar", "Vilkar")
                        .WithMany("Vedtaksvirkninger")
                        .HasForeignKey("VilkarId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AvledetFraVirkning");

                    b.Navigation("Vedtak");

                    b.Navigation("Vilkar");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.VedtaksvirkningFaktum", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Faktum", "Faktum")
                        .WithMany()
                        .HasForeignKey("FaktumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Forklaringsmodell.Domain.Entities.Vedtaksvirkning", "Vedtaksvirkning")
                        .WithMany("VedtaksvirkningFaktum")
                        .HasForeignKey("VirkningId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faktum");

                    b.Navigation("Vedtaksvirkning");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.VedtaksvirkningVurdering", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Vedtaksvirkning", "Vedtaksvirkning")
                        .WithMany("VedtaksvirkningVurdering")
                        .HasForeignKey("VirkningId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Forklaringsmodell.Domain.Entities.Vurdering", "Vurdering")
                        .WithMany()
                        .HasForeignKey("VurderingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vedtaksvirkning");

                    b.Navigation("Vurdering");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Vilkar", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Regel", "Regel")
                        .WithMany()
                        .HasForeignKey("RegelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Regel");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.VilkarRettskilde", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Rettskilde", "Rettskilde")
                        .WithMany("VilkarRettskilde")
                        .HasForeignKey("RettskildeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Forklaringsmodell.Domain.Entities.Vilkar", "Vilkar")
                        .WithMany("VilkarRettskilde")
                        .HasForeignKey("VilkarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rettskilde");

                    b.Navigation("Vilkar");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Vurdering", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Regel", "Regel")
                        .WithMany("Vurderinger")
                        .HasForeignKey("RegelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Forklaringsmodell.Domain.Entities.Sak", "Sak")
                        .WithMany("Vurderinger")
                        .HasForeignKey("SakId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Regel");

                    b.Navigation("Sak");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.VurderingFaktum", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Faktum", "Faktum")
                        .WithMany("VurderingFaktum")
                        .HasForeignKey("FaktumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Forklaringsmodell.Domain.Entities.Vurdering", "Vurdering")
                        .WithMany("VurderingFaktum")
                        .HasForeignKey("VurderingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faktum");

                    b.Navigation("Vurdering");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.VurderingReferanse", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Vurdering", "RefererteVurdering")
                        .WithMany()
                        .HasForeignKey("RefererteVurderingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Forklaringsmodell.Domain.Entities.Vurdering", "Vurdering")
                        .WithMany("RefererteVurderinger")
                        .HasForeignKey("VurderingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RefererteVurdering");

                    b.Navigation("Vurdering");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.VurderingRettskilde", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Rettskilde", "Rettskilde")
                        .WithMany("VurderingRettskilde")
                        .HasForeignKey("RettskildeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Forklaringsmodell.Domain.Entities.Vurdering", "Vurdering")
                        .WithMany("VurderingRettskilde")
                        .HasForeignKey("VurderingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rettskilde");

                    b.Navigation("Vurdering");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Faktum", b =>
                {
                    b.Navigation("Avledninger");

                    b.Navigation("FaktumRettskilde");

                    b.Navigation("VurderingFaktum");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Forklaringslogg", b =>
                {
                    b.Navigation("Oppforinger");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Kilde", b =>
                {
                    b.Navigation("Faktum");

                    b.Navigation("KildeRettskilde");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Regel", b =>
                {
                    b.Navigation("RegelRettskilde");

                    b.Navigation("Vurderinger");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Rettskilde", b =>
                {
                    b.Navigation("FaktumRettskilde");

                    b.Navigation("KildeRettskilde");

                    b.Navigation("RegelRettskilde");

                    b.Navigation("VilkarRettskilde");

                    b.Navigation("VurderingRettskilde");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Sak", b =>
                {
                    b.Navigation("Faktum");

                    b.Navigation("Partsmedvirkninger");

                    b.Navigation("Relasjoner");

                    b.Navigation("Vedtak");

                    b.Navigation("Vurderinger");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Vedtak", b =>
                {
                    b.Navigation("Forklaringslogg");

                    b.Navigation("Virkninger");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Vedtaksvirkning", b =>
                {
                    b.Navigation("AvledeteVirkninger");

                    b.Navigation("VedtaksvirkningFaktum");

                    b.Navigation("VedtaksvirkningVurdering");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Vilkar", b =>
                {
                    b.Navigation("Vedtaksvirkninger");

                    b.Navigation("VilkarRettskilde");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Vurdering", b =>
                {
                    b.Navigation("RefererteVurderinger");

                    b.Navigation("VurderingFaktum");

                    b.Navigation("VurderingRettskilde");
                });
#pragma warning restore 612, 618
        }
    }
}
