// <auto-generated />
using System;
using Forklaringsmodell.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forklaringsmodell.Infrastructure.Migrations
{
    [DbContext(typeof(ForklaringsmodellDbContext))]
    partial class ForklaringsmodellDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Faktum", b =>
                {
                    b.Property<Guid>("FaktumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AvledetFraFaktumId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("InnhentetTidspunkt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KildeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SakId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Struktur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Verdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FaktumId");

                    b.HasIndex("AvledetFraFaktumId");

                    b.HasIndex("KildeId");

                    b.HasIndex("SakId");

                    b.ToTable("Faktum", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Forklaringslogg", b =>
                {
                    b.Property<Guid>("LoggId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VedtakId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoggId");

                    b.HasIndex("VedtakId")
                        .IsUnique();

                    b.ToTable("Forklaringslogger", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.ForklaringsloggOppforing", b =>
                {
                    b.Property<Guid>("OppforingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LoggId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReferanseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("OppforingId");

                    b.HasIndex("LoggId");

                    b.HasIndex("Type", "ReferanseId");

                    b.ToTable("ForklaringsloggOppforinger", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Kilde", b =>
                {
                    b.Property<Guid>("KildeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Autoritativ")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("KildeId");

                    b.ToTable("Kilder", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Partsmedvirkning", b =>
                {
                    b.Property<Guid>("MedvirkningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Innhold")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SakId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Tidspunkt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("MedvirkningId");

                    b.HasIndex("SakId");

                    b.ToTable("Partsmedvirkninger", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Regel", b =>
                {
                    b.Property<Guid>("RegelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RettskildeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Teknologi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("RegelId");

                    b.HasIndex("RettskildeId");

                    b.ToTable("Regler", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Rettskilde", b =>
                {
                    b.Property<Guid>("RettskildeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EliReferanse")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Paragraf")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("VersjonDato")
                        .HasColumnType("TEXT");

                    b.HasKey("RettskildeId");

                    b.ToTable("Rettskilder", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Sak", b =>
                {
                    b.Property<Guid>("SakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Opprettet")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SistEndret")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tittel")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("SakId");

                    b.ToTable("Saker", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Vedtak", b =>
                {
                    b.Property<Guid>("VedtakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AutomatiseringsGrad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SakId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Tidspunkt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Utfall")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("VedtakId");

                    b.HasIndex("SakId");

                    b.ToTable("Vedtak", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Vurdering", b =>
                {
                    b.Property<Guid>("VurderingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beregningsspor")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Eskalert")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ForkastedeUtfall")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hovedhensyn")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Konfidens")
                        .HasPrecision(3, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SakId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("VurderingId");

                    b.HasIndex("RegelId");

                    b.HasIndex("SakId");

                    b.ToTable("Vurderinger", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.VurderingFaktum", b =>
                {
                    b.Property<Guid>("VurderingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FaktumId")
                        .HasColumnType("TEXT");

                    b.HasKey("VurderingId", "FaktumId");

                    b.HasIndex("FaktumId");

                    b.ToTable("VurderingFaktum", (string)null);
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Faktum", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Faktum", "AvledetFraFaktum")
                        .WithMany("Avledninger")
                        .HasForeignKey("AvledetFraFaktumId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Forklaringsmodell.Domain.Entities.Kilde", "Kilde")
                        .WithMany("Faktum")
                        .HasForeignKey("KildeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Forklaringsmodell.Domain.Entities.Sak", "Sak")
                        .WithMany("Faktum")
                        .HasForeignKey("SakId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AvledetFraFaktum");

                    b.Navigation("Kilde");

                    b.Navigation("Sak");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Forklaringslogg", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Vedtak", "Vedtak")
                        .WithOne("Forklaringslogg")
                        .HasForeignKey("Forklaringsmodell.Domain.Entities.Forklaringslogg", "VedtakId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vedtak");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.ForklaringsloggOppforing", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Forklaringslogg", "Forklaringslogg")
                        .WithMany("Oppforinger")
                        .HasForeignKey("LoggId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Forklaringslogg");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Partsmedvirkning", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Sak", "Sak")
                        .WithMany("Partsmedvirkninger")
                        .HasForeignKey("SakId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sak");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Regel", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Rettskilde", "Rettskilde")
                        .WithMany("Regler")
                        .HasForeignKey("RettskildeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rettskilde");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Vedtak", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Sak", "Sak")
                        .WithMany("Vedtak")
                        .HasForeignKey("SakId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sak");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Vurdering", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Regel", "Regel")
                        .WithMany("Vurderinger")
                        .HasForeignKey("RegelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Forklaringsmodell.Domain.Entities.Sak", "Sak")
                        .WithMany("Vurderinger")
                        .HasForeignKey("SakId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Regel");

                    b.Navigation("Sak");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.VurderingFaktum", b =>
                {
                    b.HasOne("Forklaringsmodell.Domain.Entities.Faktum", "Faktum")
                        .WithMany("VurderingFaktum")
                        .HasForeignKey("FaktumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Forklaringsmodell.Domain.Entities.Vurdering", "Vurdering")
                        .WithMany("VurderingFaktum")
                        .HasForeignKey("VurderingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faktum");

                    b.Navigation("Vurdering");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Faktum", b =>
                {
                    b.Navigation("Avledninger");

                    b.Navigation("VurderingFaktum");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Forklaringslogg", b =>
                {
                    b.Navigation("Oppforinger");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Kilde", b =>
                {
                    b.Navigation("Faktum");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Regel", b =>
                {
                    b.Navigation("Vurderinger");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Rettskilde", b =>
                {
                    b.Navigation("Regler");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Sak", b =>
                {
                    b.Navigation("Faktum");

                    b.Navigation("Partsmedvirkninger");

                    b.Navigation("Vedtak");

                    b.Navigation("Vurderinger");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Vedtak", b =>
                {
                    b.Navigation("Forklaringslogg");
                });

            modelBuilder.Entity("Forklaringsmodell.Domain.Entities.Vurdering", b =>
                {
                    b.Navigation("VurderingFaktum");
                });
#pragma warning restore 612, 618
        }
    }
}
